#ifndef BSCH3VSHARED_GLOBAL_H
#define BSCH3VSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BSCH3VSHARED_LIBRARY)
#  define BSCH3VSHAREDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BSCH3VSHAREDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BSCH3VSHARED_GLOBAL_H
